input_username = input("Введите имя пользователя")
input_title = input("Введите заголовок")
input_content = input("Введите описание")
input_status = input("введите статус")
input_created_date =  input("Введите дату начала в формате 20 12 2025")
input_issue_date =  input("Введите дату окончанияв формате 20 12 2025")
print(input_title, input_status, input_username, input_created_date, input_issue_date)
